language: go
sudo: false
dist: trusty
env:
  global:
  - HUGO_BUILD_TAGS="extended"
git:
  depth: false
go:
  - "1.11.4"
  - tip
os:
  - linux
  - osx
  - windows
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
  exclude:
  - os: windows
    go: tip

install:
  - mkdir -p $HOME/src
  - mv $HOME/gopath/src/github.com/gohugoio/hugo $HOME/src
  - export TRAVIS_BUILD_DIR=$HOME/src/hugo
  - cd $HOME/src/hugo
  - go get github.com/magefile/mage
script:
  - go mod download
  - mage -v test
  - mage -v check
  - mage -v hugo
  - ./hugo -s docs/
  - ./hugo --renderToMemory -s docs/
  - df -h

before_install:
  # more recent version of ruby is required for sinatra
  - rvm install 2.2.4
  # gem install must be run with sudo on OSX
  - sudo gem install asciidoctor sinatra --no-ri --no-rdoc | gem install asciidoctor sinatra --no-ri --no-rdoc
  - sudo pip install docutils flask
