language: go
sudo: required
dist: precise
go:
  - 1.8.7
  - 1.9.4
  - tip
os:
  - linux
  - osx
matrix:
  allow_failures:
    - go: tip
  fast_finish: true
install:
  - go get github.com/magefile/mage
  - mage vendor
script:
  - mage hugoRace
  - mage -v check
  - ./hugo -s docs/
  - ./hugo --renderToMemory -s docs/
before_install:
  # more recent version of ruby is required for sinatra
  - rvm install 2.2.4
  # gem install must be run with sudo on OSX
  - sudo gem install asciidoctor sinatra --no-ri --no-rdoc | gem install asciidoctor sinatra --no-ri --no-rdoc
  - sudo pip install docutils flask
