init:
  - set PATH=%PATH%;C:\MinGW\bin;%GOPATH%\bin
  # Take default Ruby out of path
  - set PATH=%PATH:C:\Ruby193\bin;=%
  # Add newer Ruby to path
  - set PATH=C:\Ruby22\bin;%PATH%
  - go version
  - go env
  - ruby -v

# clones and cd's to path
clone_folder: C:\GOPATH\src\github.com\gohugoio\hugo

install:
  - gem install asciidoctor sinatra --no-ri --no-rdoc
  - pip install docutils flask
  - go get github.com/magefile/mage

build_script:
  - mage vendor hugoRace
  - mage -v check
  - hugo -s docs/
  - hugo --renderToMemory -s docs/
